# Generated by Django 5.2 on 2025-05-02 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('ziel_wert', models.IntegerField()),
                ('fortschritt', models.FloatField()),
                ('einheit', models.CharField(max_length=20)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('kategorie', models.CharField(choices=[('Gesundheit', 'Gesundheit'), ('Finanzen', 'Finanzen'), ('Karriere', 'Karriere')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
