# Generated by Django 5.2 on 2025-05-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('ziel_wert', models.IntegerField()),
                ('fortschritt', models.IntegerField()),
                ('einheit', models.CharField(max_length=20)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('kategorie', models.CharField(choices=[('Gesundheit', 'Gesundheit'), ('Finanzen', 'Finanzen'), ('Karriere', 'Karriere')])),
            ],
        ),
    ]
