# Generated by Django 5.2 on 2025-05-02 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='auto_calculate',
            field=models.BooleanField(default=False, help_text='Fortschritt automatisch aus Unterzielen berechnen'),
        ),
        migrations.AddField(
            model_name='goal',
            name='is_parent_goal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goal',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tracking.goal'),
        ),
    ]
