# Generated by Django 5.2 on 2025-05-06 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0003_alter_goal_kategorie"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="YearlyGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "year",
                    models.IntegerField(
                        choices=[
                            (2020, "2020"),
                            (2021, "2021"),
                            (2022, "2022"),
                            (2023, "2023"),
                            (2024, "2024"),
                            (2025, "2025"),
                            (2026, "2026"),
                        ],
                        default=2025,
                    ),
                ),
                ("start_value", models.FloatField()),
                ("target_value", models.FloatField()),
                ("unit", models.CharField(max_length=50)),
                ("january", models.FloatField(blank=True, null=True)),
                ("february", models.FloatField(blank=True, null=True)),
                ("march", models.FloatField(blank=True, null=True)),
                ("april", models.FloatField(blank=True, null=True)),
                ("may", models.FloatField(blank=True, null=True)),
                ("june", models.FloatField(blank=True, null=True)),
                ("july", models.FloatField(blank=True, null=True)),
                ("august", models.FloatField(blank=True, null=True)),
                ("september", models.FloatField(blank=True, null=True)),
                ("october", models.FloatField(blank=True, null=True)),
                ("november", models.FloatField(blank=True, null=True)),
                ("december", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yearly_goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
