# Generated by Django 5.2 on 2025-05-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0004_yearlygoal"),
    ]

    operations = [
        migrations.AddField(
            model_name="yearlygoal",
            name="current_value",
            field=models.FloatField(
                blank=True,
                help_text="Aktueller Stand unabhängig von monatlichen Werten",
                null=True,
            ),
        ),
    ]
